export const REVIEWS_FETCH_REQUEST = "REVIEWS_FETCH_REQUEST";
export const REVIEWS_FETCH_SUCCESS = "REVIEWS_FETCH_SUCCESS";
export const REVIEWS_FETCH_FAIL = "REVIEWS_FETCH_FAIL";

export const REVIEW_SUBMIT_REQUEST = "REVIEW_SUBMIT_REQUEST";
export const REVIEW_SUBMIT_SUCCESS = "REVIEW_SUBMIT_SUCCESS";
export const REVIEW_SUBMIT_FAIL = "REVIEW_SUBMIT_FAIL";
