export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_CART = "CLEAR_CART";
export const REPLACE_CART = "REPLACE_CART";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
